/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as ExitRouteImport } from './routes/exit'
import { Route as CallRouteImport } from './routes/call'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitRoute = ExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRoute = CallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/exit': typeof ExitRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/exit': typeof ExitRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof CallRoute
  '/exit': typeof ExitRoute
  '/premium': typeof PremiumRoute
  '/profile': typeof ProfileRoute
  '/category/$slug': typeof CategorySlugRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/call'
    | '/exit'
    | '/premium'
    | '/profile'
    | '/category/$slug'
    | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/call'
    | '/exit'
    | '/premium'
    | '/profile'
    | '/category/$slug'
    | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/call'
    | '/exit'
    | '/premium'
    | '/profile'
    | '/category/$slug'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CallRoute: typeof CallRoute
  ExitRoute: typeof ExitRoute
  PremiumRoute: typeof PremiumRoute
  ProfileRoute: typeof ProfileRoute
  CategorySlugRoute: typeof CategorySlugRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exit': {
      id: '/exit'
      path: '/exit'
      fullPath: '/exit'
      preLoaderRoute: typeof ExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call': {
      id: '/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof CallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CallRoute: CallRoute,
  ExitRoute: ExitRoute,
  PremiumRoute: PremiumRoute,
  ProfileRoute: ProfileRoute,
  CategorySlugRoute: CategorySlugRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
